"""create deviations table

Revision ID: 7f9827c5fe6d
Revises: 
Create Date: 2026-09-25 11:51:46.947885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9827c5fe6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=False),
    sa.Column('date_of_occurrence', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('product_material', sa.String(length=255), nullable=False),
    sa.Column('batch_lot_number', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_impact', sa.Text(), nullable=False),
    sa.Column('initial_severity', sa.String(length=50), nullable=False),
    sa.Column('ai_impact', sa.Text(), nullable=True),
    sa.Column('ai_impact_reason', sa.Text(), nullable=True),
    sa.Column('ai_severity', sa.String(length=50), nullable=True),
    sa.Column('ai_severity_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deviations_id'), 'deviations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deviations_id'), table_name='deviations')
    op.drop_table('deviations')
    # ### end Alembic commands ###
